name: Secret Token Example

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Python Script
        run: |
          echo "import requests" > main.py
          echo "import os" >> main.py
          echo "api_key = os.getenv('API_KEY')" >> main.py
          echo "response = requests.get('https://httpbin.org/bearer', headers={'Authorization': f'Bearer {api_key}'})" >> main.py
          echo "print(response.status_code)" >> main.py
          python3 main.py
