name: Secret Token Example

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create Python Script
        run: |
          echo "import requests" > main.py
          echo "import os" >> main.py
          echo "api_key = os.getenv('API_KEY')" >> main.py
          echo "response = requests.get('https://httpbin.org/bearer', headers={'Authorization': f'Bearer {api_key}'})" >> main.py
          echo "print('Status Code:', response.status_code)" >> main.py
          echo "print('Response JSON:', response.json())" >> main.py

      - name: Run Python Script with Secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python3 main.py


